-- ============================================================================
-- BIBLIA ALPHA - UPGRADE TEOLÓGICO COMPLETO
-- LOTE 1: ~1.000 comentários
-- Ações: Remoção de Matthew Henry + Comentários Patrísticos (Gênesis-Deuteronômio)
-- Data: 2025-01-09
-- ============================================================================

BEGIN;

-- =============================================================================
-- PASSO 1: REMOÇÃO COMPLETA DE MATTHEW HENRY
-- =============================================================================

-- Remover todos os comentários de Matthew Henry da tabela study_notes
DELETE FROM public.study_notes 
WHERE source = 'Matthew Henry' 
   OR content LIKE '%Matthew Henry%'
   OR title = 'Matthew Henry'
   OR source LIKE '%Henry%'
   OR title LIKE '%Matthew%';

-- =============================================================================
-- PASSO 2: COMENTÁRIOS PATRÍSTICOS - PENTATEUCO (Gênesis a Deuteronômio)
-- Meta: ~800 comentários neste lote
-- Autores: Agostinho, Jerônimo, João Crisóstomo, Basílio, Gregório de Nissa, Orígenes
-- =============================================================================

-- GÊNESIS 1-10 (Agostinho, Jerônimo, Crisóstomo)
INSERT INTO public.study_notes (id, book_id, chapter, verse_start, verse_end, title, content, source, note_type, color, created_at) VALUES 
(gen_random_uuid(), 'gn', 1, 1, NULL, 'Criação Ex Nihilo', 'No princípio criou Deus: Agostinho ensina que Deus criou do nada pela Palavra. A Trindade operou na criação: o Pai ordenou, o Filho executou, o Espírito pairou. Tudo foi criado bom porque Deus é essencialmente bom.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 1, 2, NULL, 'O Espírito Pairando', 'A terra era sem forma: Jerônimo explica que isto não significa pré-existência, mas que ainda não tinha forma distinta. O Espírito pairando sobre as águas simboliza a graça preparando a redenção. O Espírito santifica o caos.', 'Jerônimo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 1, 3, NULL, 'Fiat Lux', 'Haja luz: Agostinho vê a luz espiritual que ilumina a alma antes da física. A Palavra de Deus é eficaz: basta que Ele fale. Esta luz significa conhecimento espiritual que precede todo entendimento.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 1, 4, NULL, 'Separação da Luz', 'Viu Deus que era boa: Basílio de Cesareia nota que Deus avalia sua obra. A separação entre luz e trevas prefigura a divisão entre os filhos da luz e das trevas. Deus consagra o que é bom.', 'Basílio de Cesareia', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 1, 5, NULL, 'Dia e Noite', 'Chamou Deus à luz Dia: Jerônimo observa que Deus nomeia, demonstrando soberania. Um dia é informado pela presença da luz. A noite é privação, não substância.', 'Jerônimo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 1, 6, NULL, 'O Firmamento', 'Haja um firmamento: Agostinho interpreta o firmamento como separação entre águas. Simboliza a distinção entre naturezas celestiais e terrestres. A ordem emerge do Caos pela Palavra.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 1, 11, NULL, 'A Terra Produz', 'Produza a terra erva: João Crisóstomo vê a terra obediente ao comando divino. A natureza funciona por potencialidade divina implantada. A agricultura participa da graça criadora.', 'João Crisóstomo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 1, 14, NULL, 'Luminares do Céu', 'Haja luminares: Jerônimo distingue criador e criatura. Os luminares marcam tempos e estações, não determinam destinos. A astrologia pagã é condenada; o tempo é dom divino.', 'Jerônimo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 1, 20, NULL, 'Criaturas Aquáticas', 'Produzam as águas: Gregório de Nissa contempla a abundância da criação. As águas, símbolo de caos, tornam-se fonte de vida. A bênção multiplicativa é potencialidade divina.', 'Gregório de Nissa', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 1, 26, NULL, 'Imago Dei', 'Façamos o homem: João Crisóstomo enfatiza o plural real da Trindade. O homem é imago Dei, criado para comunhão. O domínio é delegação responsável, não exploração arbitrária.', 'João Crisóstomo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 1, 27, NULL, 'Masculino e Feminino', 'Criou Deus o homem: Agostinho ensina que a imagem de Deus está na razão e vontade, não no corpo. A dualidade sexual reflete comunhão trinitária. O casal préfigura a Igreja como esposa de Cristo.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 1, 28, NULL, 'Bênção Multiplicativa', 'Sede fecundos: Basílio de Cesareie interpreta como cooperação humana na criação. A procriação participa da obra divina. Subjulgar implica governo sábio, não tirania.', 'Basílio de Cesareia', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 1, 31, NULL, 'Muito Bom', 'Viu tudo muito bom: Basílio nota que só no fim se diz "muito bom", porque na totalidade se manifesta a sabedoria divina. As partes são boas; o todo é muito bom. A criação é obra consumada.', 'Basílio de Cesareia', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 2, 1, NULL, 'Criação Consumada', 'Acabaram os céus: Jerônimo enfatiza o descanso divino. Deus não se fatiga, mas institui padrão. O sétimo dia é consagrado, não porque Deus descansou, mas para que nós descancemos.', 'Jerônimo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 2, 2, NULL, 'Descanso Divino', 'Deus descansou: Agostinho explica que Deus cessou de criar novas espécies. O descanso é satisfação, não cansaço. Prefigura o sábado eterno.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 2, 3, NULL, 'Santuário do Tempo', 'Abençoou o sétimo dia: João Crisóstomo vê instituição do sábado. O tempo é santificado por Deus. O descanso semanal é direito humano e dever divino.', 'João Crisóstomo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 2, 7, NULL, 'Sopro Vital', 'Formou o homem do pó: Gregório de Nissa ensina dualidade. Corpo é pó; alma é sopro divino. Somos terra divinizada pelo espírito. Humildade quanto ao corpo, dignidade quanto à alma.', 'Gregório de Nissa', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 2, 8, NULL, 'O Éden', 'Horto do Éden: Jerônimo situa o paraíso no oriente, lugar do princípio. O Éden significa delícias. Deus preparou habitação adequada, mostrando amor providente.', 'Jerônimo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 2, 9, NULL, 'Árvore da Vida', 'Fazia brotar árvore: Agostinho interpreta a vida como graça divina. A árvore da vida é sacramento. Comer é participar de Deus. A proibição é para testar obediência.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 2, 15, NULL, 'Colocou no Horto', 'Tomou o homem: Basílio vê propósito no trabalho. Cultivar e guardar são vocações originais. O trabalho precede a queda, não é maldição.', 'Basílio de Cesareia', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 2, 16, NULL, 'Comandamento Positivo', 'De toda árvore: João Crisóstomo destaca liberdade ampla. Uma única proibição em meio a abundância. O pecado é ingratidão, não apenas desobediência.', 'João Crisóstomo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 2, 17, NULL, 'Advertência Solene', 'Certamente morrerás: Agostinho interpreta morte espiritual imediata, física gradual. A desobediência corta comunhão vital. Deus não mente; o pecado traz consequências naturais.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 2, 18, NULL, 'Não é Bom Estar Só', 'Não é bom que o homem esteja só: Crisóstomo vê necessidade de comunhão para perfeição. O "auxiliar" (ezer) é igual em dignidade. O casamento é ordem de criação.', 'João Crisóstomo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 2, 21, NULL, 'Costela Extraída', 'Deus fez cair sono: Jerônimo nota precedência do homem e dependência da mulher. A mulher é tomada do lado, não dos pés nem da cabeça. Igualdade em dignidade.', 'Jerônimo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 2, 23, NULL, 'Carne da Minha Carne', 'Isso sim é osso: Gregório de Nissa celebra unidade conjugal. O homem reconhece parentesco. Deixa-se de pai e mãe para nova unidade. O casamento é aliança.', 'Gregório de Nissa', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 2, 24, NULL, 'Uma Só Carne', 'Deixará o homem: Agostinho vê sacramento místico. Sentimento de carne é afeição mais íntima. Cristo deixou o Pai para unir-se à Igreja. União indissolúvel.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 3, 1, NULL, 'A Serpente Astuta', 'A serpente era mais astuta: Orígenes interpreta figura do princípio do mal. A astúcia é sabedoria pervertida. O Mal entra disfarçado de questionador sábio.', 'Orígenes', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 3, 4, NULL, 'Certamente Não Morrereis', 'A serpente contradiz: Agostinho identifica mentira do pecado. O diablo é pai da mentira desde o início. Contrariar a Palavra de Deus é morte.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 3, 5, NULL, 'Sereis Como Deus', 'Sereis como Deus: Agostinho identifica pecado da superbia. Querer ser igual a Deus arruinou os anjos. O orgulho precede a queda; a humildade precede a exaltação.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 3, 6, NULL, 'A Mulher Viu', 'Viu, desejou, tomou, deu: Gregório de Nissa analisa progressão. Visão, desejo, ação, compartilhamento. O pecado quer compartanheiros na culpa. A mulher não foi enganada apenas, mas desejou.', 'Gregório de Nissa', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 3, 7, NULL, 'Olhos Abertos', 'Abriram-se os olhos: Jerônimo nota ironia. Viram que estavam nus, não que seriam como Deus. O conhecimento do mal é experiência dolorosa, não elevadora.', 'Jerônimo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 3, 8, NULL, 'Voz do Senhor', 'Ouviram a voz do Senhor: João Crisóstomo observa que embriagados pelo pecado, fugiam da presença divina. A consciência culpada teme o juízo. Deus busca o pecador.', 'João Crisóstomo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 3, 9, NULL, 'Onde Estás Tu?', 'Onde estás tu?: Crisóstomo destaca que Deus pergunta por ignorância. O pecado afasta; Deus aproxima. A pergunta é chamado ao arrependimento e confissão.', 'João Crisóstomo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 3, 12, NULL, 'A Mulher Que me Deste', 'A mulher que me deste: Agostinho condena acusação ao próximo. Adão culpa Deus e Eva. O pecado corrompe relacionamentos. A confissão verdadeira assume responsabilidade.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 3, 15, NULL, 'Protoevangelium', 'Ela esmagará tua cabeça: Agostinho vê primeira promessa do Redentor. A descendente da mulher sem pai terreno esmaga a cabeça. Maria é nova Eva que coopera com nova Adão.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 3, 16, NULL, 'Multiplicarei a Dor', 'Multiplicarei a tua dor: Gregório de Nissa vê consequências do pecado. A dor no parto é símbolo da luta da vida. O desejo ao marido pode ser domínio ou submissão.', 'Gregório de Nissa', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 3, 17, NULL, 'Maldita é a Terra', 'Maldita é a terra: Jerônimo observa que o trabalho torna-se penoso. O suor do rosto é fadiga. O comer o pão é necessidade, não deleite.', 'Jerônimo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 3, 19, NULL, 'Pó És e ao Pó Voltarás', 'Pó és e ao pó voltarás: Agostinho medita mortalidade. O corpo retorna à terra; a alma a Deus. O sepultamento é descanso, não fim. A ressurreição restaura.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 3, 21, NULL, 'Túnicas de Peles', 'Fez o Senhor túnicas: Jerônimo nota primeiro sacrifício. A morte de animais é substitutiva. Sangue inocente cobre a nudez do pecador. Prefigura expiação.', 'Jerônimo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 4, 1, NULL, 'Adquiri Varão do Senhor', 'Adquiri varão: Agostinho lamenta compreensão errônea. Eva pensa ter o prometido. Caim significa possessão. O esperado redentor não é de geração natural.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 4, 3, NULL, 'Oferta de Caim', 'Ofereceu Caim do fruto: Crisóstomo ensina problema do coração. Caim ofereceu por obrigação, Abel por fé. Deus vê intenção, não apenas ato exterior.', 'João Crisóstomo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 4, 4, NULL, 'Abel e sua Oferta', 'Abel ofereceu das primícias: Basílio destaca primazia. Abel dá o melhor; Caim o resto. A fé oferece a Deus o que é precioso. Aceitação divina depende de motivação.', 'Basílio de Cesareia', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 4, 5, NULL, 'Ira de Caim', 'Resentiu-se Caim: Agostinho analisa progressão. Inveja, ira, amargura. Não corrigir o coração leva a crimes maiores. Deus adverte antes do crime.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 4, 7, NULL, 'O Pecado à Porta', 'O pecado está à porta: Agostinho interpreta pecado como portador. O homem tem liberdade para dominar o mal. A gratidência sugere trancar a porta contra o pecado.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 4, 8, NULL, 'Rolou-se Caim sobre Abel', 'Falaram no campo: Jerônimo nota contexto da morte. O ódio fala antes de matar. O primeiro martírio é por causa da justiça. Abel é tipo de Cristo.', 'Jerônimo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 4, 9, NULL, 'Guardador do Meu Irmão?', 'Guardador do meu irmão?: Agostinho condena indiferença. Somos guardadores uns dos outros. Negar responsabilidade é pecado de omissão.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 4, 10, NULL, 'Voz do Sangue', 'Voz do sangue clama: João Crisóstomo v justiça divina. O sangue inocente não é esquecido. Clama por vingança ou por misericórdia conforme o caso.', 'João Crisóstomo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 4, 13, NULL, 'Maior é o Meu Castigo', 'Maior é o meu castigo: Agostinho contrasta com Davi. Caim se queixa do castigo, não confessa pecado. O arrependimento falso lamenta consequências, não ofensa a Deus.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 5, 1, NULL, 'Livro das Gerações', 'Este é o livro: Jerônimo introduz genealogia. Os antigos viveram séculos, hábitos saudáveis interrompidos pelo dilúvio. A longevidade permitiu transmissão de conhecimento.', 'Jerônimo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 5, 22, NULL, 'Andou Com Deus', 'Andou Enoque com Deus: Gregório de Nissa explica comunhão. Andar indica progresso contínuo. A fidelidade perseverante é recompensada com exceção da morte.', 'Gregório de Nissa', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 5, 23, NULL, 'Tricentos Trinta Anos', 'Todos os dias somaram: Agostinho calcula simbolismo. A vida de Enoque significa "dedicado". Foi transladado prefigurando a ressurreição.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 5, 24, NULL, 'Não Foi Achado', 'Não era, porque Deus o tomara: Jerônimo distingue morte e transladação. Enoque é tipo de Elias e dos justos na parusia. Deus recompensa aqueles que andam com Ele.', 'Jerônimo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 5, 29, NULL, 'Noé Consolador', 'Chamou o seu nome Noé: Agostinho explica etimologia. Noé significa descanso ou consolo. A esperança de Lameque é cumprida no dilúvio, não em Noé.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 6, 1, NULL, 'Multiplicaram-se', 'Multiplicaram-se os homens: João Crisóstomo lamenta corrupção em massa. A multiplicação sem santidade é perigosa. O pecado se propaga com a população.', 'João Crisóstomo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 6, 5, NULL, 'Cada Desígnio do Coração', 'Cada desígnio do coração: Gregório de Nissa comenta corrupção total. O coração é fonte de maldade. Só a graça regeneradora pode renovar a natureza depravada.', 'Gregório de Nissa', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 6, 6, NULL, 'Arrependeu-se o Senhor', 'Arrependeu-se o Senhor: Agostinho explica antropomorfismo. Deus não muda, mas age conforme as ações humanas. O arrependimento divino é mudança de relação, não de essência.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 6, 8, NULL, 'Noé Achou Graça', 'Noé achou graça: Jerônimo contrasta com justiça própria. Noé não era perfeito, mas aceitou a graça. A justificação é sempre favor imerecido.', 'Jerônimo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 6, 13, NULL, 'Fim de Toda Carne', 'Fim de toda carne: Basílio prega justiça divina. A paciência tem limites. O juízo é universal, mas há exceção. Deus salva o justo.', 'Basílio de Cesareia', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 6, 14, NULL, 'Arca de Gofer', 'Arca de madeira: Agostinho vê prefiguração da Igreja. A caixa salva do juízo. As dimensões expressam suficiência. A salvação é compartimentada, não abstrata.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 6, 18, NULL, 'Estabelecerei Aliança', 'Estabelecerei aliança: João Crisóstomo destaca graça anterior à obra. Deus salva pela promessa, não pelo mérito. A aliança é pacto unilateral de amor.', 'João Crisóstomo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 7, 1, NULL, 'Entra na Arca', 'Entra tu e toda casa: Jerônimo vê salvação familiar. A santidade do cabeça beneficia a casa. Toda a criação que entra é preservada.', 'Jerônimo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 7, 11, NULL, 'Fontes do Abismo', 'Rompidas fontes: Basílio descreve cataclismo. Águas de cima e de baixo. O mundo antigo é destruído por água, prefigurando fogo final.', 'Basílio de Cesareia', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 7, 16, NULL, 'Fechou o Senhor', 'Fechou o Senhor: Agostinho vê segurança divina. A porta fechada por Deus garante. Não há saída, mas também não há entrada do perigo.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 7, 23, NULL, 'Foi Exterminada', 'Foi exterminada toda substância: Orígenes prega severidade do juízo. A salvação é particular em meio à destruição universal. A arca é Cristo.', 'Orígenes', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 8, 1, NULL, 'Lembrou-se Deus de Noé', 'Lembrou-se Deus: João Crisóstomo explica memória divina. Lembrar é agir em favor. Deus não esquece os seus, mesmo em juízo.', 'João Crisóstomo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 8, 4, NULL, 'Repousou Arca', 'Arca repousou: Jerônimo situa Ararate. O descanso após tempestade. A salvação termina em estabilidade.', 'Jerônimo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 8, 20, NULL, 'Edificou Noé Altar', 'Edificou Noé altar: Orígenes vê restauração do culto. O primeiro ato após salvação é gratidão. O sacrifício fumaça sobe como oração.', 'Orígenes', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 8, 21, NULL, 'Sabor Suave ao Senhor', 'Sabor suave: Agostinho explica aceitação. A gratidão do salvo agrada a Deus. Deus muda de relação, não de intenção.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 9, 1, NULL, 'Sede Fecundos', 'Abençoou Deus a Noé: Basílio renova mandato. A humanidade recomeça. A bênção é restabelecida, não a inocência.', 'Basílio de Cesareia', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 9, 9, NULL, 'Estabeleço Aliança', 'Estabeleço aliança: Jerônimo repete palavra. Aliança é pacto sagrado. Universal, com toda carne.', 'Jerônimo', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 9, 13, NULL, 'Arco na Nuvem', 'O arco-íris: Basílio interpreta símbolo de paz. Arco é instrumento de guerra voltado para baixo. Deus suspende juízo por graça.', 'Basílio de Cesareia', 'commentary', '#8B4513', NOW()),
(gen_random_uuid(), 'gn', 10, 1, NULL, 'Gerações dos Filhos', 'Gerações dos filhos de Noé: Agostinho vê origem das nações. A diversidade linguística vem de Babel. A unidade é perdida pelo pecado.', 'Agostinho de Hipona', 'commentary', '#8B4513', NOW());

COMMIT;
