
-- Translate place_type to Portuguese
UPDATE public.bible_places SET place_type = CASE place_type
  WHEN 'mountain' THEN 'montanha'
  WHEN 'road' THEN 'estrada'
  WHEN 'garden' THEN 'jardim'
  WHEN 'island' THEN 'ilha'
  WHEN 'stone heap' THEN 'monte de pedras'
  WHEN 'special' THEN 'especial'
  WHEN 'river' THEN 'rio'
  WHEN 'valley' THEN 'vale'
  WHEN 'ford' THEN 'vau'
  WHEN 'people group' THEN 'grupo étnico'
  WHEN 'forest' THEN 'floresta'
  WHEN 'canal' THEN 'canal'
  WHEN 'wadi' THEN 'riacho seco'
  WHEN 'natural area' THEN 'área natural'
  WHEN 'tree' THEN 'árvore'
  WHEN 'spring' THEN 'fonte'
  WHEN 'hill' THEN 'colina'
  WHEN 'rock' THEN 'rocha'
  WHEN 'structure' THEN 'estrutura'
  WHEN 'promontory' THEN 'promontório'
  WHEN 'fortification' THEN 'fortaleza'
  WHEN 'field' THEN 'campo'
  WHEN 'altar' THEN 'altar'
  WHEN 'pool' THEN 'tanque'
  WHEN 'mountain range' THEN 'cadeia de montanhas'
  WHEN 'region' THEN 'região'
  WHEN 'settlement' THEN 'cidade'
  WHEN 'gate' THEN 'portão'
  WHEN 'well' THEN 'poço'
  WHEN 'campsite' THEN 'acampamento'
  WHEN 'cliff' THEN 'penhasco'
  WHEN 'district in settlement' THEN 'bairro'
  WHEN 'body of water' THEN 'corpo d''água'
  WHEN 'room' THEN 'sala'
  WHEN 'mountain pass' THEN 'desfiladeiro'
  WHEN 'hall' THEN 'salão'
  ELSE place_type
END;

-- Translate major biblical place names to Portuguese
UPDATE public.bible_places SET name = CASE name
  WHEN 'Jerusalem' THEN 'Jerusalém'
  WHEN 'Bethlehem' THEN 'Belém'
  WHEN 'Egypt' THEN 'Egito'
  WHEN 'Babylon' THEN 'Babilônia'
  WHEN 'Samaria' THEN 'Samaria'
  WHEN 'Nazareth' THEN 'Nazaré'
  WHEN 'Capernaum' THEN 'Cafarnaum'
  WHEN 'Galilee' THEN 'Galileia'
  WHEN 'Jordan' THEN 'Jordão'
  WHEN 'Jericho' THEN 'Jericó'
  WHEN 'Sinai' THEN 'Sinai'
  WHEN 'Hebron' THEN 'Hebrom'
  WHEN 'Damascus' THEN 'Damasco'
  WHEN 'Nineveh' THEN 'Nínive'
  WHEN 'Tyre' THEN 'Tiro'
  WHEN 'Sidon' THEN 'Sidom'
  WHEN 'Antioch' THEN 'Antioquia'
  WHEN 'Corinth' THEN 'Corinto'
  WHEN 'Ephesus' THEN 'Éfeso'
  WHEN 'Athens' THEN 'Atenas'
  WHEN 'Rome' THEN 'Roma'
  WHEN 'Philippi' THEN 'Filipos'
  WHEN 'Thessalonica' THEN 'Tessalônica'
  WHEN 'Sodom' THEN 'Sodoma'
  WHEN 'Gomorrah' THEN 'Gomorra'
  WHEN 'Bethany' THEN 'Betânia'
  WHEN 'Bethel' THEN 'Betel'
  WHEN 'Shiloh' THEN 'Siló'
  WHEN 'Shechem' THEN 'Siquém'
  WHEN 'Cana' THEN 'Caná'
  WHEN 'Gilead' THEN 'Gileade'
  WHEN 'Moab' THEN 'Moabe'
  WHEN 'Edom' THEN 'Edom'
  WHEN 'Assyria' THEN 'Assíria'
  WHEN 'Persia' THEN 'Pérsia'
  WHEN 'Ur' THEN 'Ur'
  WHEN 'Haran' THEN 'Harã'
  WHEN 'Beersheba' THEN 'Berseba'
  WHEN 'Dead Sea' THEN 'Mar Morto'
  WHEN 'Red Sea' THEN 'Mar Vermelho'
  WHEN 'Sea of Galilee' THEN 'Mar da Galileia'
  WHEN 'Mediterranean Sea' THEN 'Mar Mediterrâneo'
  WHEN 'Mount Sinai' THEN 'Monte Sinai'
  WHEN 'Mount Carmel' THEN 'Monte Carmelo'
  WHEN 'Mount Zion' THEN 'Monte Sião'
  WHEN 'Mount Hermon' THEN 'Monte Hermom'
  WHEN 'Mount Olivet' THEN 'Monte das Oliveiras'
  WHEN 'Mount Tabor' THEN 'Monte Tabor'
  WHEN 'Mount Nebo' THEN 'Monte Nebo'
  WHEN 'Mount Ararat' THEN 'Monte Ararate'
  WHEN 'Euphrates' THEN 'Eufrates'
  WHEN 'Tigris' THEN 'Tigre'
  WHEN 'Nile' THEN 'Nilo'
  WHEN 'Crete' THEN 'Creta'
  WHEN 'Cyprus' THEN 'Chipre'
  WHEN 'Malta' THEN 'Malta'
  WHEN 'Patmos' THEN 'Patmos'
  WHEN 'Laodicea' THEN 'Laodiceia'
  WHEN 'Pergamum' THEN 'Pérgamo'
  WHEN 'Sardis' THEN 'Sardes'
  WHEN 'Smyrna' THEN 'Esmirna'
  WHEN 'Thyatira' THEN 'Tiatira'
  WHEN 'Philadelphia' THEN 'Filadélfia'
  WHEN 'Galatia' THEN 'Galácia'
  WHEN 'Caesarea' THEN 'Cesareia'
  WHEN 'Iconium' THEN 'Icônio'
  WHEN 'Lystra' THEN 'Listra'
  WHEN 'Derbe' THEN 'Derbe'
  WHEN 'Troas' THEN 'Trôade'
  WHEN 'Miletus' THEN 'Mileto'
  WHEN 'Colossae' THEN 'Colossos'
  WHEN 'Gaza' THEN 'Gaza'
  WHEN 'Joppa' THEN 'Jope'
  WHEN 'Lydda' THEN 'Lida'
  WHEN 'Sharon' THEN 'Sarom'
  WHEN 'Lebanon' THEN 'Líbano'
  WHEN 'Armageddon' THEN 'Armagedom'
  WHEN 'Paran' THEN 'Parã'
  WHEN 'Kadesh' THEN 'Cades'
  WHEN 'Dothan' THEN 'Dotã'
  WHEN 'Gilgal' THEN 'Gilgal'
  WHEN 'Mizpah' THEN 'Mispá'
  WHEN 'Ramah' THEN 'Ramá'
  WHEN 'Sheba' THEN 'Sabá'
  WHEN 'Ophir' THEN 'Ofir'
  WHEN 'Tarshish' THEN 'Társis'
  WHEN 'Zarephath' THEN 'Sarepta'
  WHEN 'Megiddo' THEN 'Megido'
  ELSE name
END
WHERE name IN (
  'Jerusalem','Bethlehem','Egypt','Babylon','Samaria','Nazareth','Capernaum','Galilee','Jordan','Jericho',
  'Sinai','Hebron','Damascus','Nineveh','Tyre','Sidon','Antioch','Corinth','Ephesus','Athens',
  'Rome','Philippi','Thessalonica','Sodom','Gomorrah','Bethany','Bethel','Shiloh','Shechem','Cana',
  'Gilead','Moab','Edom','Assyria','Persia','Ur','Haran','Beersheba','Dead Sea','Red Sea',
  'Sea of Galilee','Mediterranean Sea','Mount Sinai','Mount Carmel','Mount Zion','Mount Hermon',
  'Mount Olivet','Mount Tabor','Mount Nebo','Mount Ararat','Euphrates','Tigris','Nile','Crete',
  'Cyprus','Malta','Patmos','Laodicea','Pergamum','Sardis','Smyrna','Thyatira','Philadelphia',
  'Galatia','Caesarea','Iconium','Lystra','Derbe','Troas','Miletus','Colossae','Gaza','Joppa',
  'Lydda','Sharon','Lebanon','Armageddon','Paran','Kadesh','Dothan','Gilgal','Mizpah','Ramah',
  'Sheba','Ophir','Tarshish','Zarephath','Megiddo'
);
